Use TestDatabase;

CREATE TABLE PRODUCT(
ID INT PRIMARY KEY IDENTITY ,
NAME NVARCHAR(30) NOT NULL 
);

CREATE TABLE CATEGORY(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(30) NOT NULL
);

CREATE TABLE PRODUCT_CATEGORY(
PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCT(ID) ON DELETE CASCADE,
CATEGORY_ID INT FOREIGN KEY REFERENCES CATEGORY(ID) ON DELETE CASCADE,
);

INSERT PRODUCT VALUES('Пельмени'),('Яблоки'),('Йогурт'),('Замороженные овощи'),('Замороженные колбасы');
INSERT CATEGORY VALUES('Заморозка'),('Овощи'),('Мясные продукты');

INSERT PRODUCT_CATEGORY VALUES (1,1),(1,3),(2,2),(4,1),(4,2),(5,1),(5,3);

SELECT PRODUCT.NAME AS 'Название продукта', CATEGORY.NAME  AS 'Название категории'
FROM PRODUCT
LEFT JOIN PRODUCT_CATEGORY ON PRODUCT.ID = PRODUCT_ID
LEFT JOIN CATEGORY ON CATEGORY_ID = CATEGORY.ID
